# Generated by Django 5.2.17 on 2026-08-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Κατηγορίας Ενδιαφέροντος')),
                ('slug', models.SlugField(help_text='URL friendly όνομα (π.χ. fagito-kai-poto)', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Εικονίδο από το FontAwesome (π.χ. fa-solid fa-landmark)', max_length=50)),
            ],
            options={
                'verbose_name': 'Κατηγορία',
                'verbose_name_plural': 'Κατηγορίες',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Όνομα πόλης')),
                ('slug', models.SlugField(help_text='URL friendly όνομα (π.χ. athens-greece)', max_length=200, unique=True)),
                ('country', models.CharField(max_length=100, verbose_name='Χώρα')),
                ('description', models.TextField(verbose_name='Περιγραφή / Οδηγός για την πόλη')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Εικόνα προορισμού για εξώφυλλο')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Γεωγραφικό Πλάτος')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Γεωγραφικό Μήκος')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Προτεινόμενος Προορισμός;')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Προορισμός',
                'verbose_name_plural': 'Προοορισμοί',
            },
        ),
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος Αξιοθέατου')),
                ('description', models.TextField(verbose_name='Περιγραφή Αξιοθέατου')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Διεύθυνση')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Γεωγραφικό Πλάτος')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Γεωγραφικό Μήκος')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pois/', verbose_name='Φωτογραφία αξιοθέατου')),
                ('price_range', models.CharField(choices=[('€', 'Budget / Οικονομικό'), ('€€', 'Moderate / Μεσαίας Κλίμακας'), ('€€€', 'Expensive / Ακριβό'), ('€€€€', 'Luxury / Πολύ ακριβό')], default='€€', max_length=10, verbose_name='Κλίμακα Τιμής')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('categories', models.ManyToManyField(related_name='pois', to='destinations.category', verbose_name='Κατηγορίες')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='destinations.destination', verbose_name='Προορισμός')),
            ],
            options={
                'verbose_name': 'Αξιοθέατο / Σημείο Ενδιαφέροντος',
                'verbose_name_plural': 'Αξιοθέατα / Σημεία Ενδιαφέροντος',
            },
        ),
    ]
